from reportlab.lib.pagesizes import letter
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, HRFlowable
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from io import BytesIO
from datetime import datetime


def generate_pdf(report_text: str, patient_id: str) -> bytes:
    """
    Takes the raw report string and patient ID,
    returns a clean PDF as bytes ready for download.
    """
    buffer = BytesIO()
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        rightMargin=0.75 * inch,
        leftMargin=0.75 * inch,
        topMargin=0.75 * inch,
        bottomMargin=0.75 * inch,
    )

    styles = getSampleStyleSheet()

    # Custom styles
    title_style = ParagraphStyle(
        "CustomTitle",
        parent=styles["Heading1"],
        fontSize=18,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
    )

    subtitle_style = ParagraphStyle(
        "CustomSubtitle",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#555555"),
        spaceAfter=2,
        alignment=TA_CENTER,
    )

    disclaimer_style = ParagraphStyle(
        "Disclaimer",
        parent=styles["Normal"],
        fontSize=8,
        textColor=colors.HexColor("#cc0000"),
        spaceAfter=6,
        alignment=TA_CENTER,
        fontName="Helvetica-Bold",
    )

    body_style = ParagraphStyle(
        "CustomBody",
        parent=styles["Normal"],
        fontSize=10,
        textColor=colors.HexColor("#1a1a1a"),
        spaceAfter=4,
        leading=15,
        fontName="Helvetica",
    )

    section_style = ParagraphStyle(
        "Section",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#1a1a2e"),
        spaceAfter=4,
        spaceBefore=8,
        fontName="Helvetica-Bold",
    )

    # Build the content
    story = []

    # Header
    story.append(Paragraph("DentalAI — OPG Analysis Report", title_style))
    story.append(Paragraph(f"Patient ID: {patient_id}", subtitle_style))
    story.append(
        Paragraph(
            f"Generated: {datetime.now().strftime('%B %d, %Y at %I:%M %p')}",
            subtitle_style,
        )
    )
    story.append(Spacer(1, 0.1 * inch))
    story.append(
        Paragraph(
            "⚠️ AI-GENERATED DRAFT — MUST BE REVIEWED BY A LICENSED DENTAL PROFESSIONAL",
            disclaimer_style,
        )
    )
    story.append(HRFlowable(width="100%", thickness=1, color=colors.HexColor("#1a1a2e")))
    story.append(Spacer(1, 0.1 * inch))

    # Parse and render the report text line by line
    lines = report_text.split("\n")
    for line in lines:
        stripped = line.strip()

        if not stripped:
            story.append(Spacer(1, 0.05 * inch))
            continue

        # Section dividers (━━━ lines)
        if stripped.startswith("━"):
            story.append(
                HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc"))
            )
            continue

        # Section headers (all caps lines)
        if stripped.isupper() and len(stripped) > 3 and not stripped.startswith("⚠"):
            story.append(Paragraph(stripped, section_style))
            continue

        # Priority flags — preserve emoji
        if stripped.startswith(("🔴", "🟡", "🟢", "⚠️")):
            flag_style = ParagraphStyle(
                "Flag",
                parent=body_style,
                fontSize=10,
                textColor=colors.HexColor("#1a1a1a"),
                leftIndent=10,
                fontName="Helvetica-Bold",
            )
            story.append(Paragraph(stripped, flag_style))
            continue

        # Regular body lines
        story.append(Paragraph(stripped, body_style))

    # Footer
    story.append(Spacer(1, 0.2 * inch))
    story.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor("#cccccc")))
    story.append(
        Paragraph(
            "This report was generated by DentalAI for educational and workflow assistance only. "
            "Not FDA-cleared for diagnostic use. All findings must be independently verified "
            "by a licensed dental professional before any clinical decision is made.",
            ParagraphStyle(
                "FooterDisclaimer",
                parent=styles["Normal"],
                fontSize=7,
                textColor=colors.HexColor("#888888"),
                alignment=TA_CENTER,
                spaceBefore=6,
            ),
        )
    )

    doc.build(story)
    pdf_bytes = buffer.getvalue()
    buffer.close()
    return pdf_bytes